const assert = require('assert');
const { W, newGame, spawn, turn, step } = require('./sim.js');
const g = newGame();
const a = spawn(g, 'a', 'A');
a.body = [[5, 5], [4, 5], [3, 5]]; g.food = [[6, 5], [0, 0], [1, 1]];
step(g);
assert.strictEqual(a.body.length, 4, 'grows on food');
assert.strictEqual(a.score, 1);
assert.strictEqual(g.food.length, 3, 'food refilled');
turn(a, [-1, 0]); assert.deepStrictEqual(a.next, [1, 0], '180 ignored');
turn(a, [0, 1]); assert.deepStrictEqual(a.next, [0, 1]);
a.body = [[W - 1, 5], [W - 2, 5]]; a.dir = a.next = [1, 0]; step(g);
assert.strictEqual(a.alive, false, 'wall kills');
for (let i = 0; i < 20; i++) step(g);
assert.strictEqual(a.alive, true, 'respawns');
const b = spawn(g, 'b', 'B');
assert.notStrictEqual(a.color, b.color, 'distinct colors');
a.body = [[10, 10], [9, 10], [8, 10]]; a.dir = a.next = [1, 0];
b.body = [[12, 10], [13, 10], [14, 10]]; b.dir = b.next = [-1, 0];
step(g);
assert(!a.alive && !b.alive, 'head-on kills both');
console.log('ok');
